### ISSUE TITLE
Secret Hash

### ISSUE THREAD

**Issue by Kovaloff** [black-bits/laravel-cognito-auth#11]
Hello! I have an issue with the client secret ! Now my application is configured so as not to use a aws client secret, is it possible to add a check to this field and only in case this AWS_COGNITO_CLIENT_SECRET exists, add this parameter to the aws client query ?

**Comment by araeuchle** [comment]
Hey, thanks for your issue here. 
Could you please either post your AWS Cognito config here or send it to us per email to hello@blackbits.io?

Also feel free to create a pull request and we will be checking it out. 
Thank you very much and have a great Sunday.
