### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by jvrsolis** [black-bits/laravel-cognito-auth#12]
Is there a way currently to send to cognito a remember device request? Since cognito can be used to login to multiple devices I wanted to see if it was possible here allow device remembering here. Also I think remembering devices may be a no go 🙅‍♂️ using non mobile languages because of API restrictions but I also wanted to ask about MFA support I know for sure there are API points for that but not sure if this package includes support for that too.

**Comment by oheck** [comment]
Remembering devices should be possible. The mobile SDKs provide better support through wrapped functionality that supports that feature more natively. Same goes for MFA.

https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/

Right now we do not support both unfortunately, but let me check if we have a timeline for MFA in this project.

**Comment by oheck** [comment]
No MFA planned so far.
