### ISSUE TITLE
Can not fetch the AWS_COGNITO_KEY and AWS_COGNITO_SECRET.

### ISSUE THREAD

**Issue by eric0324** [black-bits/laravel-cognito-auth#13]
Hi

I try to create a new IAM Role with the following Access Rights:

AmazonCognitoDeveloperAuthenticatedIdentities
AmazonCognitoPowerUser
AmazonESCognitoAccess

But I cannot fetch the AWS_COGNITO_KEY and AWS_COGNITO_SECRET?

Please help me understand it

Thanks.

**Comment by araeuchle** [comment]
Hey and sorry for the late reply.
If you create a new IAM role, you will be asked on the first page for the access type. Here you need to select the first checkbox: Programmatic access. Then you create a custom group and add those access rights to it.
Once done, you click on create user and you should see a page where you get two credentials, those are your AWS_COGNITO_KEY and AWS_COGNITO_SECRET. It must be called something like access key id and secret access key. Something like that.
I hope that helps you and you can fetch the credentials.

Best Regards.

**Comment by eric0324** [comment]
@araeuchle 

I try to create a new IAM role

![Imgur](https://i.imgur.com/pPJBEJC.png)

but I can not found `Programmatic access`

**Comment by pratikjoshibyjus** [comment]
same here @eric0324  @araeuchle I too cant find Programmatic acceess

**Comment by pratikjoshibyjus** [comment]
I got it, its simply access key secret key.
Create user say A.
goto users >> https://console.aws.amazon.com/iam/home?region=us-east-1#/users and
Assign him 3 policies.
