### ISSUE TITLE
Cannot get AccessToken.

### ISSUE THREAD

**Issue by mongveasna** [black-bits/laravel-cognito-auth#16]
Hi,
Can I get access token of cognito (https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminInitiateAuth.html) for each user after login or signup to use it later?

Thanks

**Comment by oheck** [comment]
Sorry, but we don't have time to help with specific implementation issues / questions.

**Comment by waqleh** [comment]
AuthenticationResult should be stored somewhere, especially the access token.
