### ISSUE TITLE
Can this work localy?

### ISSUE THREAD

**Issue by foo123** [black-bits/laravel-cognito-auth#23]
We are making an AWS app using laravel and we are thinking of using amazon cognito for user authentication.
It is wonderful this package is available (although in beta). 

However I have one question maybe stupid..
Can this be used while developing localy on my local computer or does it need tofunction only inside EC2 or beanstalk? I mean while my app is in dev and it doesnt have a public url yet.

**Comment by kuldeepcis** [comment]
yes, it'll work on locally

**Comment by foo123** [comment]
Great thank you!
