### ISSUE TITLE
The security token included in the request is invalid : need to know from where to pick up/generate AWS_COGNITO_KEY, AWS_COGNITO_SECRET from AWS account.

### ISSUE THREAD

**Issue by pratikjoshibyjus** [black-bits/laravel-cognito-auth#34]
-------------------------------------------
I also have another question

Where to add following files/traits >>>>>
Can you please give me sample example where should I include it. Thanks

Our package is providing you 5 traits you can just add to your Auth Controllers to get our package running.

BlackBits\LaravelCognitoAuth\Auth\AuthenticatesUsers
BlackBits\LaravelCognitoAuth\Auth\RegistersUsers
BlackBits\LaravelCognitoAuth\Auth\ResetsPasswords
BlackBits\LaravelCognitoAuth\Auth\SendsPasswordResetEmails
BlackBits\LaravelCognitoAuth\Auth\VerifiesEmails

Thank you

**Comment by oheck** [comment]
Does that help?

"Now you walk through the AuthControllers and swap out the Laravel specific traits with our traits."

https://blackbits.io/blog/laravel-authentication-with-aws-cognito
