### ISSUE TITLE
Is there example implementation using this package ?

### ISSUE THREAD

**Issue by cecepsaefull** [black-bits/laravel-cognito-auth#38]
I start using AWS Cognito for user management with laravel. 
Is there example implementation laravel using this package ? Or sample functional for Login and register

**Comment by oheck** [comment]
https://blackbits.io/blog/laravel-authentication-with-aws-cognito

**Comment by ceceps** [comment]
Thanks' for your response butg that reference need to update content some code different, is not using this package directly
